services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\Flusher\Flusher:
        public: true

    Endroid\Flusher\FlusherEntityManager:
        arguments: [ '@Endroid\Flusher\FlusherEntityManager.inner' ]
        calls:
            - ['setFlusher', ['@Endroid\Flusher\Flusher']]
        decorates: doctrine.orm.default_entity_manager
